/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antsstyle.pollimagemaker.GUI;

import java.awt.dnd.DropTarget;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Ant
 */
public class PrimaryDisplayPanel extends javax.swing.JPanel {
    
    private static final Logger LOGGER = LogManager.getLogger();

    /**
     * Creates new form PrimaryDisplayPanel
     */
    public PrimaryDisplayPanel() {
        initComponents();
        connectToDragDrop();
    }
    
    
    private void connectToDragDrop() {
        DNDListener dnd = new DNDListener();
        new DropTarget(this, dnd);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideToolBar = new javax.swing.JToolBar();
        goToImageMakerButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        goToSettingsButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        goToAboutButton = new javax.swing.JButton();
        displayAreaPanel = new javax.swing.JPanel();

        sideToolBar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        sideToolBar.setFloatable(false);
        sideToolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sideToolBar.setRollover(true);
        sideToolBar.setMaximumSize(new java.awt.Dimension(114, 1000));
        sideToolBar.setMinimumSize(new java.awt.Dimension(114, 200));
        sideToolBar.setPreferredSize(new java.awt.Dimension(114, 200));

        goToImageMakerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToImageMakerButton.setText("Image Maker");
        goToImageMakerButton.setFocusable(false);
        goToImageMakerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToImageMakerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToImageMakerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToImageMakerButtonActionPerformed(evt);
            }
        });
        sideToolBar.add(goToImageMakerButton);
        sideToolBar.add(jSeparator1);

        goToSettingsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToSettingsButton.setText("Settings");
        goToSettingsButton.setFocusable(false);
        goToSettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToSettingsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSettingsButtonActionPerformed(evt);
            }
        });
        sideToolBar.add(goToSettingsButton);
        sideToolBar.add(jSeparator2);

        goToAboutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goToAboutButton.setText("About");
        goToAboutButton.setFocusable(false);
        goToAboutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        goToAboutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        goToAboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToAboutButtonActionPerformed(evt);
            }
        });
        sideToolBar.add(goToAboutButton);

        displayAreaPanel.setMaximumSize(new java.awt.Dimension(1292, 659));
        displayAreaPanel.setMinimumSize(new java.awt.Dimension(400, 550));
        displayAreaPanel.setPreferredSize(new java.awt.Dimension(400, 550));

        javax.swing.GroupLayout displayAreaPanelLayout = new javax.swing.GroupLayout(displayAreaPanel);
        displayAreaPanel.setLayout(displayAreaPanelLayout);
        displayAreaPanelLayout.setHorizontalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        displayAreaPanelLayout.setVerticalGroup(
            displayAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addComponent(displayAreaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToImageMakerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToImageMakerButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getMainPanel());
    }//GEN-LAST:event_goToImageMakerButtonActionPerformed

    private void goToSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSettingsButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getSettingsPanel());
    }//GEN-LAST:event_goToSettingsButtonActionPerformed

    private void goToAboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToAboutButtonActionPerformed
        GUI.getInstance().switchPanels(GUI.getAboutPanel());
    }//GEN-LAST:event_goToAboutButtonActionPerformed

        /**
     * Sets the panel to display inside this one.
     *
     * @param panel The panel to display.
     */
    protected void setDisplayAreaPanel(javax.swing.JPanel panel) {
        displayAreaPanel = panel;
    }

    /**
     * Gets the panel currently being displayed inside this one.
     *
     * @return The panel being displayed inside this panel.
     */
    protected javax.swing.JPanel getDisplayAreaPanel() {
        return displayAreaPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayAreaPanel;
    private javax.swing.JButton goToAboutButton;
    private javax.swing.JButton goToImageMakerButton;
    private javax.swing.JButton goToSettingsButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    protected javax.swing.JToolBar sideToolBar;
    // End of variables declaration//GEN-END:variables
}
